import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import Product from './models/Product.js';
import Service from './models/Service.js';
import Testimonial from './models/Testimonial.js';
import Lead from './models/Lead.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// Try to load .env from root, but fallback to default if not found
dotenv.config({ path: path.join(__dirname, '../.env') });

const products = [
    {
        id: 'cctv-1',
        name: 'HD Dome Camera 2MP',
        category: 'cctv',
        description: 'High-definition dome camera with night vision',
        fullDescription: 'Professional 2MP HD dome camera with IR night vision up to 30m, weatherproof IP66 rating, and wide dynamic range for clear images in all lighting conditions.',
        image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=400',
        features: ['2MP Full HD', 'Night Vision 30m', 'IP66 Weatherproof', 'Wide Angle Lens'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹2,500',
        rentPrice: '₹500/month',
    },
    {
        id: 'cctv-2',
        name: '4-Channel DVR System',
        category: 'cctv',
        description: 'Complete 4-channel DVR with 1TB storage',
        fullDescription: 'Complete surveillance solution with 4-channel DVR, 1TB HDD, H.265 compression, remote viewing via mobile app, and motion detection alerts.',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
        features: ['4 Channels', '1TB Storage', 'Mobile App', 'Motion Detection'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹8,500',
        rentPrice: '₹1,500/month',
    },
    {
        id: 'cctv-3',
        name: '8-Channel NVR System',
        category: 'cctv',
        description: 'Network video recorder for IP cameras',
        fullDescription: 'Advanced 8-channel NVR supporting 4K cameras, 2TB storage, POE ports for easy installation, and AI-powered video analytics.',
        image: 'https://images.unsplash.com/photo-1606567595334-d39972c85dfd?w=400',
        features: ['8 Channels', '4K Support', 'POE Ports', 'AI Analytics'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹15,000',
        rentPrice: '₹2,500/month',
    },
    {
        id: 'gps-1',
        name: 'Vehicle GPS Tracker',
        category: 'gps',
        description: 'Real-time vehicle tracking with geofencing',
        fullDescription: 'Advanced GPS tracker with real-time location tracking, geofencing alerts, trip history, fuel monitoring, and driver behavior analysis.',
        image: 'https://images.unsplash.com/photo-1609587312208-cea54be969e7?w=400',
        features: ['Real-time Tracking', 'Geofencing', 'Trip History', 'Fuel Monitoring'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹3,500',
        rentPrice: '₹600/month',
    },
    {
        id: 'gps-2',
        name: 'Asset Tracker Mini',
        category: 'gps',
        description: 'Compact tracker for valuable assets',
        fullDescription: 'Compact and discreet GPS tracker for assets with long battery life, magnetic mounting, and tamper alerts.',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
        features: ['Compact Design', 'Long Battery', 'Magnetic Mount', 'Tamper Alert'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹2,800',
        rentPrice: '₹450/month',
    },
    {
        id: 'bio-1',
        name: 'Fingerprint Attendance System',
        category: 'biometric',
        description: 'Employee attendance with fingerprint scanner',
        fullDescription: 'Reliable fingerprint attendance system with 3000 user capacity, USB/WiFi connectivity, and cloud-based attendance reports.',
        image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400',
        features: ['3000 Users', 'WiFi Enabled', 'Cloud Reports', 'Battery Backup'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹6,500',
        rentPrice: '₹1,200/month',
    },
    {
        id: 'bio-2',
        name: 'Face Recognition Terminal',
        category: 'biometric',
        description: 'Touchless face recognition for access control',
        fullDescription: 'Advanced face recognition terminal with mask detection, fever screening, and access control integration.',
        image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400',
        features: ['Face Recognition', 'Mask Detection', 'Fever Screening', 'Access Control'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹18,000',
        rentPrice: '₹3,000/month',
    },
    {
        id: 'laptop-1',
        name: 'Business Laptop i5',
        category: 'laptop-desktop',
        description: 'Intel Core i5, 8GB RAM, 256GB SSD',
        fullDescription: 'Professional business laptop with 11th Gen Intel Core i5, 8GB DDR4 RAM, 256GB NVMe SSD, 14" FHD display, and Windows 11 Pro.',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
        features: ['Intel i5 11th Gen', '8GB RAM', '256GB SSD', 'Windows 11 Pro'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹45,000',
        rentPrice: '₹4,500/month',
    },
    {
        id: 'laptop-2',
        name: 'Workstation Desktop i7',
        category: 'laptop-desktop',
        description: 'High-performance desktop for professionals',
        fullDescription: 'Powerful workstation with Intel Core i7, 16GB RAM, 512GB SSD, dedicated graphics, and multiple display support.',
        image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=400',
        features: ['Intel i7', '16GB RAM', '512GB SSD', 'Dedicated GPU'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹65,000',
        rentPrice: '₹6,000/month',
    },
    {
        id: 'laptop-3',
        name: 'Refurbished Laptop i3',
        category: 'laptop-desktop',
        description: 'Budget-friendly refurbished laptop',
        fullDescription: 'Quality refurbished laptop with Intel Core i3, 4GB RAM, 128GB SSD, fully tested and certified with 6-month warranty.',
        image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400',
        features: ['Intel i3', '4GB RAM', '128GB SSD', '6-Month Warranty'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹18,000',
        rentPrice: '₹1,800/month',
    },
    {
        id: 'printer-1',
        name: 'Laser Printer Mono',
        category: 'printers',
        description: 'Fast monochrome laser printer',
        fullDescription: 'High-speed monochrome laser printer with 30 ppm, automatic duplex printing, network ready, and mobile printing support.',
        image: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400',
        features: ['30 PPM', 'Auto Duplex', 'Network Ready', 'Mobile Print'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹12,000',
        rentPrice: '₹1,500/month',
    },
    {
        id: 'printer-2',
        name: 'Color MFP Printer',
        category: 'printers',
        description: 'Multifunction color printer with scanner',
        fullDescription: 'All-in-one color printer with print, scan, copy, and fax capabilities. Touchscreen control and high-capacity paper trays.',
        image: 'https://images.unsplash.com/photo-1544928147-79a2dbc1f389?w=400',
        features: ['Print/Scan/Copy/Fax', 'Color Printing', 'Touchscreen', 'High Capacity'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹28,000',
        rentPrice: '₹3,500/month',
    },
    {
        id: 'ipcam-1',
        name: '4MP IP Bullet Camera',
        category: 'ip-cameras',
        description: 'Outdoor IP camera with POE',
        fullDescription: '4MP IP bullet camera with Power over Ethernet, 50m IR night vision, IP67 weatherproof, and H.265 compression.',
        image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400',
        features: ['4MP Resolution', 'POE Support', '50m Night Vision', 'IP67 Rating'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹5,500',
        rentPrice: '₹800/month',
    },
    {
        id: 'ipcam-2',
        name: 'PTZ IP Camera',
        category: 'ip-cameras',
        description: 'Pan-Tilt-Zoom camera with auto tracking',
        fullDescription: 'Professional PTZ camera with 20x optical zoom, 360° pan, auto-tracking, and smart video analytics.',
        image: 'https://images.unsplash.com/photo-1610642372651-fe6e7bc160a1?w=400',
        features: ['20x Optical Zoom', '360° Pan', 'Auto Tracking', 'Video Analytics'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹35,000',
        rentPrice: '₹5,000/month',
    },
    {
        id: 'monitor-1',
        name: '24" Full HD Monitor',
        category: 'led-monitors',
        description: 'Professional 24-inch LED monitor',
        fullDescription: '24-inch Full HD IPS monitor with 75Hz refresh rate, slim bezels, eye care technology, and multiple connectivity options.',
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
        features: ['24" FHD IPS', '75Hz Refresh', 'Eye Care', 'HDMI/VGA'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹9,500',
        rentPrice: '₹1,200/month',
    },
    {
        id: 'monitor-2',
        name: '27" 4K UHD Monitor',
        category: 'led-monitors',
        description: 'Ultra HD monitor for professionals',
        fullDescription: '27-inch 4K UHD monitor with HDR support, USB-C connectivity, height adjustable stand, and factory calibrated colors.',
        image: 'https://images.unsplash.com/photo-1547119957-637f8679db1e?w=400',
        features: ['27" 4K UHD', 'HDR Support', 'USB-C', 'Color Calibrated'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹28,000',
        rentPrice: '₹3,500/month',
    },
    {
        id: 'server-1',
        name: 'Tower Server Entry',
        category: 'servers',
        description: 'Entry-level tower server for SMBs',
        fullDescription: 'Entry-level tower server with Intel Xeon processor, 16GB ECC RAM, 1TB SATA, and hardware RAID controller.',
        image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400',
        features: ['Intel Xeon', '16GB ECC RAM', '1TB Storage', 'Hardware RAID'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹85,000',
        rentPrice: '₹8,000/month',
    },
    {
        id: 'server-2',
        name: '42U Server Rack Cabinet',
        category: 'servers',
        description: 'Standard 42U server rack enclosure',
        fullDescription: 'Professional 42U server rack cabinet with cable management, cooling fans, PDU support, and lockable doors.',
        image: 'https://images.unsplash.com/photo-1506399558188-acca6f8cbf41?w=400',
        features: ['42U Capacity', 'Cable Management', 'Cooling Fans', 'Lockable'],
        canBuy: true,
        canRent: true,
        canRepair: false,
        price: '₹45,000',
        rentPrice: '₹4,500/month',
    },
    {
        id: 'network-1',
        name: '24-Port Gigabit Switch',
        category: 'network',
        description: 'Managed gigabit ethernet switch',
        fullDescription: '24-port managed gigabit switch with VLAN support, QoS, port mirroring, and web-based management interface.',
        image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400',
        features: ['24 Ports', 'Gigabit Speed', 'VLAN Support', 'Web Management'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹18,000',
        rentPrice: '₹2,000/month',
    },
    {
        id: 'network-2',
        name: 'Enterprise WiFi Router',
        category: 'network',
        description: 'High-performance business router',
        fullDescription: 'Enterprise-grade WiFi 6 router with mesh support, VPN server, load balancing, and advanced security features.',
        image: 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=400',
        features: ['WiFi 6', 'Mesh Support', 'VPN Server', 'Load Balancing'],
        canBuy: true,
        canRent: true,
        canRepair: true,
        price: '₹12,000',
        rentPrice: '₹1,500/month',
    },
];

const services = [
    {
        id: 'new-sales',
        title: 'New Product Sales',
        description: 'Get the latest IT hardware and security equipment from top brands with warranty and after-sales support.',
        icon: '🛒',
        features: [
            'Genuine products from authorized dealers',
            'Manufacturer warranty included',
            'Professional installation available',
            'Technical support and training',
            'Competitive pricing',
        ],
        image: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600',
    },
    {
        id: 'refurbished',
        title: 'Refurbished Products',
        description: 'Quality refurbished IT equipment at budget-friendly prices, fully tested and certified.',
        icon: '♻️',
        features: [
            'Thoroughly tested and certified',
            '6-month warranty on all items',
            'Up to 50% savings vs new',
            'Environmentally responsible',
            'Same-day availability',
        ],
        image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600',
    },
    {
        id: 'repair',
        title: 'Repair & AMC Services',
        description: 'Expert repair services and Annual Maintenance Contracts to keep your equipment running smoothly.',
        icon: '🔧',
        features: [
            'Certified technicians',
            'Quick turnaround time',
            'Genuine spare parts',
            'On-site and off-site support',
            'Preventive maintenance',
        ],
        image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600',
    },
    {
        id: 'rental',
        title: 'Rental Services',
        description: 'Flexible rental options for short-term projects, events, or businesses that need scalability.',
        icon: '📋',
        features: [
            'Daily, weekly, monthly plans',
            'Latest equipment available',
            'Technical support included',
            'Easy upgrade options',
            'No heavy upfront investment',
        ],
        image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600',
    },
];

const testimonials = [
    {
        id: 'test-1',
        name: 'Rajesh Kumar',
        designation: 'IT Manager',
        industry: 'Corporate IT',
        message: 'YANTRAQ has been our trusted partner for over 5 years. Their CCTV and server solutions have transformed our infrastructure. The team responds quickly to any issues, and their AMC service gives us peace of mind knowing our systems are always maintained.',
        rating: 5,
        isActive: true,
        createdAt: '2024-01-15',
    },
    {
        id: 'test-2',
        name: 'Dr. Priya Sharma',
        designation: 'Principal',
        industry: 'Education',
        message: 'We deployed biometric attendance systems and CCTV cameras across our campus with YANTRAQ. The installation was professional, and the ongoing support has been exceptional. Our campus security has improved significantly.',
        rating: 5,
        isActive: true,
        createdAt: '2024-02-20',
    },
    {
        id: 'test-3',
        name: 'Amit Verma',
        designation: 'Operations Director',
        industry: 'Manufacturing',
        message: 'The GPS tracking solutions from YANTRAQ helped us optimize our fleet operations. Real-time monitoring and geofencing have reduced our fuel costs by 20%. Their technical expertise and reliable service make them stand out.',
        rating: 5,
        isActive: true,
        createdAt: '2024-03-10',
    },
    {
        id: 'test-4',
        name: 'Neha Agarwal',
        designation: 'Founder & CEO',
        industry: 'Startup',
        message: 'As a growing startup, we needed flexible IT solutions without heavy upfront costs. YANTRAQ\'s rental services for laptops and networking equipment allowed us to scale quickly. Their team understood our needs and delivered beyond expectations.',
        rating: 5,
        isActive: true,
        createdAt: '2024-04-05',
    },
    {
        id: 'test-5',
        name: 'Sandeep Patel',
        designation: 'Head of Operations',
        industry: 'Enterprise',
        message: 'YANTRAQ manages our entire IT infrastructure across 3 locations. From servers to network switches to security systems — everything runs smoothly. Their proactive maintenance approach has virtually eliminated downtime for us.',
        rating: 5,
        isActive: true,
        createdAt: '2024-05-12',
    },
    {
        id: 'test-6',
        name: 'Kavita Reddy',
        designation: 'Administrator',
        industry: 'Healthcare',
        message: 'We trust YANTRAQ for all our IT needs at our multi-specialty hospital. Their understanding of healthcare requirements, combined with enterprise-grade solutions, makes them the perfect partner. Highly recommended!',
        rating: 5,
        isActive: true,
        createdAt: '2024-06-18',
    },
];

const leads = [
    {
        id: 'lead-1',
        name: 'Vikram Singh',
        email: 'vikram@techcorp.com',
        phone: '+91 98765 11111',
        productService: '8-Channel NVR System',
        enquiryType: 'buy',
        message: 'We need 4 NVR systems for our new office building.',
        status: 'new',
        createdAt: '2024-12-10T10:30:00',
    },
    {
        id: 'lead-2',
        name: 'Sunita Menon',
        email: 'sunita@eduschool.org',
        phone: '+91 98765 22222',
        productService: 'Fingerprint Attendance System',
        enquiryType: 'buy',
        message: 'Looking for biometric systems for 500+ students and staff.',
        status: 'in-progress',
        createdAt: '2024-12-08T14:15:00',
    },
    {
        id: 'lead-3',
        name: 'Rahul Kapoor',
        email: 'rahul@startupinc.io',
        phone: '+91 98765 33333',
        productService: 'Business Laptop i5',
        enquiryType: 'rent',
        message: 'Need 20 laptops for our team for 6 months.',
        status: 'new',
        createdAt: '2024-12-12T09:45:00',
    },
    {
        id: 'lead-4',
        name: 'Meera Joshi',
        email: 'meera@manufacturing.co',
        phone: '+91 98765 44444',
        productService: 'Vehicle GPS Tracker',
        enquiryType: 'buy',
        message: 'Fleet tracking for 15 delivery vehicles.',
        status: 'closed',
        createdAt: '2024-12-01T11:20:00',
    },
    {
        id: 'lead-5',
        name: 'Arjun Nair',
        email: 'arjun@hospital.care',
        phone: '+91 98765 55555',
        productService: 'Tower Server Entry',
        enquiryType: 'repair',
        message: 'Server not booting, need urgent repair.',
        status: 'in-progress',
        createdAt: '2024-12-11T16:00:00',
    },
];

const seedDB = async () => {
    try {
        const conn = await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/yantraq');
        console.log(`MongoDB Connected: ${conn.connection.host}`);

        // Clear existing data
        await Product.deleteMany({});
        await Service.deleteMany({});
        await Testimonial.deleteMany({});
        await Lead.deleteMany({});
        console.log('Cleared existing data...');

        // Insert new data (exclude local 'id' so Mongo creates '_id')
        const insertProducts = products.map(({ id, ...rest }: any) => rest);
        const insertServices = services.map(({ id, ...rest }: any) => rest);
        const insertTestimonials = testimonials.map(({ id, ...rest }: any) => rest);
        const insertLeads = leads.map(({ id, ...rest }: any) => rest);

        await Product.insertMany(insertProducts);
        await Service.insertMany(insertServices);
        await Testimonial.insertMany(insertTestimonials);
        await Lead.insertMany(insertLeads);

        console.log('Database seeded successfully!');
        process.exit();
    } catch (error) {
        console.error('Error seeding database:', error);
        process.exit(1);
    }
};

seedDB();
